name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure clippy and rustfmt
        run: rustup component add clippy rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy check
        run: cargo clippy --all-features --workspace -- -D warnings

  test-and-docs:
    name: Tests & Documentation
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C link-arg=-fuse-ld=lld"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo nextest run --locked --all-features --workspace

      - name: Check documentation
        run: cargo doc --no-deps --document-private-items --all-features --workspace
        env:
          RUSTDOCFLAGS: "-D warnings"

